spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://payment-db:5432/paymentdb
    username: pay
    password: pay
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

# ─── move this out of `spring:` ───────────────────────────────────────────────────
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true